package org.jerakeen.flame;

import java.util.HashMap;

public class ServiceLookup implements Comparable {
    static HashMap<String, ServiceLookup> lookup = new HashMap<String, ServiceLookup>();
    public static void register(String name, String description, int drawable, int priority) {
        ServiceLookup s = new ServiceLookup(name, description, drawable, priority);
        lookup.put(s.name, s);
    }

    public static ServiceLookup get(String name) {
        if (lookup.isEmpty()) firstRun();
        return lookup.get(name);
    }

    String name;
    String description;
    int drawable;
    int priority;

    public ServiceLookup(String name, String description, int drawable, int priority) {
        super();
        this.name = name;
        this.description = description;
        this.drawable = drawable;
        this.priority = priority;
    }

    static void firstRun() {
        // custom things not in master list
        register("acp-sync", "Internet gateway device configuration protocol", R.drawable.router, 0);
        register("appletv-v2", "Apple TV", R.drawable.tv, 5);
        register("airplay", "Airplay", R.drawable.note, 4);
        register("slipstreamrem", "Slipstream / Spotify?", R.drawable.note, 0); // TODO spotify only?
        register("hudson", "Hudson build server console", R.drawable.spiderweb, 0);
        register("apple-mobdev", "iOS remote development / sync", R.drawable.iphone, 0); // TODO not sure about this one

        // atc
        // 16122


        // this list built with the service_list_builder script, though I've added my own custom icons, which
        // is a pain
        register("1password", "1Password Password Manager data sharing and synchronization protocol", R.drawable.key, 0);
        register("a-d-sync", "Altos Design Synchronization protocol", R.drawable.gear2, 0);
        register("abi-instrument", "Applied Biosystems Universal Instrument Framework", R.drawable.gear2, 0);
        register("accessdata-f2d", "FTK2 Database Discovery Service", R.drawable.gear2, 0);
        register("accessdata-f2w", "FTK2 Backend Processing Agent Service", R.drawable.gear2, 0);
        register("accessone", "Strix Systems 5S/AccessOne protocol", R.drawable.gear2, 0);
        register("accountedge", "MYOB AccountEdge", R.drawable.gear2, 0);
        register("acrobatsrv", "Adobe Acrobat", R.drawable.gear2, 0);
        register("actionitems", "ActionItems", R.drawable.gear2, 0);
        register("activeraid", "Active Storage Proprietary Device Management Protocol", R.drawable.gear2, 0);
        register("activeraid-ssl", "Encrypted transport of Active Storage Proprietary Device Management Protocol", R.drawable.gear2, 0);
        register("addressbook", "Address-O-Matic", R.drawable.gear2, 0);
        register("adobe-vc", "Adobe Version Cue", R.drawable.gear2, 0);
        register("adisk", "Automatic Disk Discovery", R.drawable.gear2, 0);
        register("adpro-setup", "ADPRO Security Device Setup", R.drawable.gear2, 0);
        register("aecoretech", "Apple Application Engineering Services", R.drawable.gear2, 0);
        register("aeroflex", "Aeroflex instrumentation and software", R.drawable.gear2, 0);
        register("afpovertcp", "Apple File Sharing", R.drawable.cloud, 0);
        register("airport", "AirPort Base Station", R.drawable.router, 3);
        register("airprojector", "AirProjector", R.drawable.gear2, 0);
        register("airsharing", "Air Sharing", R.drawable.gear2, 0);
        register("airsharingpro", "Air Sharing Pro", R.drawable.gear2, 0);
        register("amba-cam", "Ambarella Cameras", R.drawable.gear2, 0);
        register("amiphd-p2p", "P2PTapWar Sample Application from \"iPhone SDK Development\" Book", R.drawable.gear2, 0);
        register("animolmd", "Animo License Manager", R.drawable.gear2, 0);
        register("animobserver", "Animo Batch Server", R.drawable.gear2, 0);
        register("anquetsync", "Anquet map synchronization between desktop and handheld devices", R.drawable.gear2, 0);
        register("appelezvous", "Appelezvous", R.drawable.gear2, 0);
        register("apple-ausend", "Apple Audio Units", R.drawable.note, 0);
        register("apple-midi", "Apple MIDI", R.drawable.note, 0);
        register("apple-sasl", "Apple Password Server", R.drawable.key, 0);
        register("applerdbg", "Apple Remote Debug Services (OpenGL Profiler)", R.drawable.gear2, 0);
        register("appletv", "Apple TV", R.drawable.tv, 4);
        register("appletv-itunes", "Apple TV discovery of iTunes", R.drawable.note, 0);
        register("appletv-pair", "Apple TV Pairing", R.drawable.tv, 0);
        register("aquamon", "AquaMon", R.drawable.gear2, 0);
        register("asr", "Apple Software Restore", R.drawable.gear2, 0);
        register("astnotify", "Asterisk Caller-ID Notification Service", R.drawable.gear2, 0);
        register("astralite", "Astralite", R.drawable.gear2, 0);
        register("async", "address-o-sync", R.drawable.gear2, 0);
        register("atlassianapp", "Atlassian Application (JIRA, Confluence, Fisheye, Crucible, Crowd, Bamboo) discovery service", R.drawable.gear2, 0);
        register("av", "Allen Vanguard Hardware Service", R.drawable.gear2, 0);
        register("axis-video", "Axis Video Cameras", R.drawable.gear2, 0);
        register("auth", "Authentication Service", R.drawable.gear2, 0);
        register("b3d-convince", "3M Unitek Digital Orthodontic System", R.drawable.gear2, 0);
        register("babyphone", "BabyPhone", R.drawable.gear2, 0);
        register("bdsk", "BibDesk Sharing", R.drawable.gear2, 0);
        register("beacon", "Beacon Remote Service", R.drawable.gear2, 0);
        register("beamer", "Beamer Data Sharing Protocol", R.drawable.gear2, 0);
        register("beatpack", "BeatPack Synchronization Server for BeatMaker", R.drawable.gear2, 0);
        register("beep", "Xgrid Technology Preview", R.drawable.gear2, 0);
        register("bfagent", "BuildForge Agent", R.drawable.gear2, 0);
        register("bigbangchess", "Big Bang Chess", R.drawable.gear2, 0);
        register("bigbangmancala", "Big Bang Mancala", R.drawable.gear2, 0);
        register("bittorrent", "BitTorrent Zeroconf Peer Discovery Protocol", R.drawable.network, 0);
        register("blackbook", "Little Black Book Information Exchange Protocol", R.drawable.gear2, 0);
        register("bluevertise", "BlueVertise Network Protocol (BNP)", R.drawable.network, 0);
        register("bookworm", "Bookworm Client Discovery", R.drawable.gear2, 0);
        register("bootps", "Bootstrap Protocol Server", R.drawable.gear2, 0);
        register("boundaryscan", "Proprietary", R.drawable.gear2, 0);
        register("bousg", "Bag Of Unusual Strategy Games", R.drawable.controller, 0);
        register("bri", "RFID Reader Basic Reader Interface", R.drawable.gear2, 0);
        register("bsqdea", "Backup Simplicity", R.drawable.gear2, 0);
        register("busycal", "BusySync Calendar Synchronization Protocol", R.drawable.gear2, 0);
        register("caltalk", "CalTalk", R.drawable.gear2, 0);
        register("cardsend", "Card Send Protocol", R.drawable.gear2, 0);
        register("cctv", "IP and Closed-Circuit Television for Securitiy applications", R.drawable.gear2, 0);
        register("cheat", "The Cheat", R.drawable.gear2, 0);
        register("chess", "Project Gridlock", R.drawable.gear2, 0);
        register("chfts", "Fluid Theme Server", R.drawable.gear2, 0);
        register("chili", "The CHILI Radiology System", R.drawable.gear2, 0);
        register("cip4discovery", "Discovery of JDF (CIP4 Job Definition Format) enabled devices", R.drawable.gear2, 0);
        register("clipboard", "Clipboard Sharing", R.drawable.gear2, 0);
        register("clique", "Clique Link-Local Multicast Chat Room", R.drawable.gear2, 0);
        register("clscts", "Oracle CLS Cluster Topology Service", R.drawable.gear2, 0);
        register("collection", "Published Collection Object", R.drawable.gear2, 0);
        register("com-ocs-es-mcc", "ElectraStar media centre control protocol", R.drawable.gear2, 0);
        register("contactserver", "Now Contact", R.drawable.gear2, 0);
        register("corroboree", "Corroboree Server", R.drawable.gear2, 0);
        register("cpnotebook2", "NoteBook 2", R.drawable.notepad, 0);
        register("cvspserver", "CVS PServer", R.drawable.gear2, 0);
        register("cw-codetap", "CodeWarrior HTI Xscale PowerTAP", R.drawable.gear2, 0);
        register("cw-dpitap", "CodeWarrior HTI DPI PowerTAP", R.drawable.gear2, 0);
        register("cw-oncetap", "CodeWarrior HTI OnCE PowerTAP", R.drawable.gear2, 0);
        register("cw-powertap", "CodeWarrior HTI COP PowerTAP", R.drawable.gear2, 0);
        register("cytv", "CyTV", R.drawable.gear2, 0);
        register("daap", "Digital Audio Access Protocol (iTunes)", R.drawable.note, 0);
        register("dacp", "Digital Audio Control Protocol (iTunes)", R.drawable.note, 0);
        register("dancepartner", "Dance partner application for iPhone", R.drawable.gear2, 0);
        register("dataturbine", "Open Source DataTurbine Streaming Data Middleware", R.drawable.gear2, 0);
        register("device-info", "Device Info", R.drawable.gear2, 0);
        register("difi", "EyeHome", R.drawable.gear2, 0);
        register("disconnect", "DisConnect Peer to Peer Game Protocol", R.drawable.controller, 0);
        register("dist-opencl", "Distributed OpenCL discovery protocol", R.drawable.gear2, 0);
        register("distcc", "Distributed Compiler", R.drawable.gear2, 0);
        register("ditrios", "Ditrios SOA Framework Protocol", R.drawable.gear2, 0);
        register("divelogsync", "Dive Log Data Sharing and Synchronization Protocol", R.drawable.gear2, 0);
        register("dltimesync", "Local Area Dynamic Time Synchronisation Protocol", R.drawable.gear2, 0);
        register("dns-llq", "DNS Long-Lived Queries", R.drawable.gear2, 0);
        register("dns-sd", "DNS Service Discovery", R.drawable.network, 0);
        register("dns-update", "DNS Dynamic Update Service", R.drawable.gear2, 0);
        register("domain", "Domain Name Server", R.drawable.gear2, 0);
        register("dop", "Roar (Death of Productivity)", R.drawable.gear2, 0);
        register("dossier", "Vortimac Dossier Protocol", R.drawable.gear2, 0);
        register("dpap", "Digital Photo Access Protocol (iPhoto)", R.drawable.photos, 0);
        register("dropcopy", "DropCopy", R.drawable.cloud, 0);
        register("dsl-sync", "Data Synchronization Protocol for Discovery Software products", R.drawable.gear2, 0);
        register("dtrmtdesktop", "Desktop Transporter Remote Desktop Protocol", R.drawable.gear2, 0);
        register("dvbservdsc", "DVB Service Discovery", R.drawable.gear2, 0);
        register("dxtgsync", "Documents To Go Desktop Sync Protocol", R.drawable.notepad, 0);
        register("ea-dttx-poker", "Protocol for EA Downtown Texas Hold 'em", R.drawable.gear2, 0);
        register("earphoria", "Earphoria", R.drawable.gear2, 0);
        register("eb-amuzi", "Amuzi peer-to-peer session synchronization protocol", R.drawable.gear2, 0);
        register("ebms", "ebXML Messaging", R.drawable.gear2, 0);
        register("ecms", "Northrup Grumman/Mission Systems/ESL Data Flow Protocol", R.drawable.gear2, 0);
        register("ebreg", "ebXML Registry", R.drawable.gear2, 0);
        register("ecbyesfsgksc", "Net Monitor Anti-Piracy Service", R.drawable.gear2, 0);
        register("edcp", "LaCie Ethernet Disk Configuration Protocol", R.drawable.gear2, 0);
        register("egistix", "Egistix Auto-Discovery", R.drawable.gear2, 0);
        register("eheap", "Interactive Room Software Infrastructure (Event Sharing)", R.drawable.gear2, 0);
        register("embrace", "DataEnvoy", R.drawable.gear2, 0);
        register("ep", "Endpoint Protocol (EP) for use in Home Automation systems", R.drawable.gear2, 0);
        register("eppc", "Remote AppleEvents", R.drawable.gear2, 0);
        register("erp-scale", "Pocket Programs ERP-Scale Server Discovery protocol", R.drawable.gear2, 0);
        register("esp", "Extensis Server Protocol", R.drawable.gear2, 0);
        register("eucalyptus", "Eucalyptus Discovery", R.drawable.gear2, 0);
        register("eventserver", "Now Up-to-Date", R.drawable.gear2, 0);
        register("evs-notif", "EVS Notification Center Protocol", R.drawable.gear2, 0);
        register("ewalletsync", "Synchronization Protocol for Ilium Software's eWallet", R.drawable.gear2, 0);
        register("example", "Example Service Type", R.drawable.gear2, 0);
        register("exb", "Exbiblio Cascading Service Protocol", R.drawable.gear2, 0);
        register("exec", "Remote Process Execution", R.drawable.gear2, 0);
        register("extensissn", "Extensis Serial Number", R.drawable.gear2, 0);
        register("eyetvsn", "EyeTV Sharing", R.drawable.gear2, 0);
        register("facespan", "FaceSpan", R.drawable.gear2, 0);
        register("fairview", "Fairview Device Identification", R.drawable.gear2, 0);
        register("faxstfx", "FAXstf", R.drawable.gear2, 0);
        register("feed-sharing", "NetNewsWire 2.0", R.drawable.gear2, 0);
        register("firetask", "Firetask task sharing and synchronization protocol", R.drawable.gear2, 0);
        register("fish", "Fish", R.drawable.gear2, 0);
        register("fix", "Financial Information Exchange (FIX) Protocol", R.drawable.gear2, 0);
        register("fjork", "Fjork", R.drawable.gear2, 0);
        register("fl-purr", "FilmLight Cluster Power Control Service", R.drawable.gear2, 0);
        register("fmpro-internal", "FileMaker Pro", R.drawable.gear2, 0);
        register("fmserver-admin", "FileMaker Server Administration Communication Service", R.drawable.gear2, 0);
        register("fontagentnode", "FontAgent Pro", R.drawable.gear2, 0);
        register("foxtrot-serv", "FoxTrot Search Server Discovery Service", R.drawable.gear2, 0);
        register("foxtrot-start", "FoxTrot Professional Search Discovery Service", R.drawable.gear2, 0);
        register("frameforge-lic", "FrameForge License", R.drawable.gear2, 0);
        register("freehand", "FreeHand MusicPad Pro Interface Protocol", R.drawable.note, 0);
        register("frog", "Frog Navigation Systems", R.drawable.gear2, 0);
        register("ftp", "File Transfer", R.drawable.cloud, 0);
        register("ftpcroco", "Crocodile FTP Server", R.drawable.gear2, 0);
        register("fv-cert", "Fairview Certificate", R.drawable.gear2, 0);
        register("fv-key", "Fairview Key", R.drawable.gear2, 0);
        register("fv-time", "Fairview Time/Date", R.drawable.gear2, 0);
        register("garagepad", "Entrackment Client Service", R.drawable.gear2, 0);
        register("gbs-smp", "SnapMail", R.drawable.gear2, 0);
        register("gbs-stp", "SnapTalk", R.drawable.gear2, 0);
        register("gforce-ssmp", "G-Force Control via SoundSpectrum's SSMP TCP Protocol", R.drawable.gear2, 0);
        register("glasspad", "GlassPad Data Exchange Protocol", R.drawable.gear2, 0);
        register("glasspadserver", "GlassPadServer Data Exchange Protocol", R.drawable.gear2, 0);
        register("glrdrvmon", "OpenGL Driver Monitor", R.drawable.gear2, 0);
        register("gpnp", "Grid Plug and Play", R.drawable.gear2, 0);
        register("grillezvous", "Roxio ToastAnywhere(tm) Recorder Sharing", R.drawable.gear2, 0);
        register("growl", "Growl", R.drawable.network, 0);
        register("guid", "Special service type for resolving by GUID (Globally Unique Identifier)", R.drawable.gear2, 0);
        register("h323", "H.323 Real-time audio, video and data communication call setup protocol", R.drawable.gear2, 0);
        register("helix", "MultiUser Helix Server", R.drawable.gear2, 0);
        register("help", "HELP command", R.drawable.gear2, 0);
        register("hg", "Mercurial web-based repository access", R.drawable.spiderweb, 0);
        register("hinz", "HINZMobil Synchronization protocol", R.drawable.gear2, 0);
        register("hmcp", "Home Media Control Protocol", R.drawable.note, 0);
        register("home-sharing", "iTunes Home Sharing", R.drawable.note, 0);
        register("homeauto", "iDo Technology Home Automation Protocol", R.drawable.gear2, 0);
        register("honeywell-vid", "Honeywell Video Systems", R.drawable.gear2, 0);
        register("hotwayd", "Hotwayd", R.drawable.gear2, 0);
        register("howdy", "Howdy messaging and notification protocol", R.drawable.gear2, 0);
        register("hpr-bldlnx", "HP Remote Build System for Linux-based Systems", R.drawable.gear2, 0);
        register("hpr-bldwin", "HP Remote Build System for Microsoft Windows Systems", R.drawable.gear2, 0);
        register("hpr-db", "Identifies systems that house databases for the Remote Build System and Remote Test System", R.drawable.gear2, 0);
        register("hpr-rep", "HP Remote Repository for Build and Test Results", R.drawable.gear2, 0);
        register("hpr-toollnx", "HP Remote System that houses compilers and tools for Linux-based Systems", R.drawable.gear2, 0);
        register("hpr-toolwin", "HP Remote System that houses compilers and tools for Microsoft Windows Systems", R.drawable.gear2, 0);
        register("hpr-tstlnx", "HP Remote Test System for Linux-based Systems", R.drawable.gear2, 0);
        register("hpr-tstwin", "HP Remote Test System for Microsoft Windows Systems", R.drawable.gear2, 0);
        register("hs-off", "Hobbyist Software Off Discovery", R.drawable.gear2, 0);
        register("htsp", "Home Tv Streaming Protocol", R.drawable.gear2, 0);
        register("http", "World Wide Web HTML-over-HTTP", R.drawable.spiderweb, 0);
        register("https", "HTTP over SSL/TLS", R.drawable.spiderweb, 0);
        register("hydra", "SubEthaEdit", R.drawable.gear2, 0);
        register("hyperstream", "Atempo HyperStream deduplication server", R.drawable.gear2, 0);
        register("iax", "Inter Asterisk eXchange, ease-of-use NAT friendly open VoIP protocol", R.drawable.gear2, 0);
        register("ibiz", "iBiz Server", R.drawable.gear2, 0);
        register("ica-networking", "Image Capture Networking", R.drawable.photos, 0);
        register("ican", "Northrup Grumman/TASC/ICAN Protocol", R.drawable.gear2, 0);
        register("ichalkboard", "iChalk", R.drawable.gear2, 0);
        register("ichat", "iChat 1.0", R.drawable.chat, 0);
        register("iconquer", "iConquer", R.drawable.gear2, 0);
        register("idata", "Generic Data Acquisition and Control Protocol", R.drawable.gear2, 0);
        register("idsync", "SplashID Synchronization Service", R.drawable.gear2, 0);
        register("ifolder", "Published iFolder", R.drawable.gear2, 0);
        register("ihouse", "Idle Hands iHouse Protocol", R.drawable.gear2, 0);
        register("ii-drills", "Instant Interactive Drills", R.drawable.gear2, 0);
        register("ii-konane", "Instant Interactive Konane", R.drawable.gear2, 0);
        register("ilynx", "iLynX", R.drawable.gear2, 0);
        register("imap", "Internet Message Access Protocol", R.drawable.envelope, 0);
        register("imidi", "iMidi", R.drawable.note, 0);
        register("indigo-dvr", "Indigo Security Digital Video Recorders", R.drawable.gear2, 0);
        register("inova-ontrack", "Inova Solutions OnTrack Display Protocol", R.drawable.gear2, 0);
        register("idcws", "Intermec Device Configuration Web Services", R.drawable.gear2, 0);
        register("ipbroadcaster", "IP Broadcaster", R.drawable.gear2, 0);
        register("ipp", "IPP (Internet Printing Protocol)", R.drawable.printer, 0);
        register("ipspeaker", "IP Speaker Control Protocol", R.drawable.speaker, 0);
        register("irelay", "iRelay application discovery service", R.drawable.gear2, 0);
        register("irmc", "Intego Remote Management Console", R.drawable.gear2, 0);
        register("iscsi", "Internet Small Computer Systems Interface (iSCSI)", R.drawable.gear2, 0);
        register("isparx", "iSparx", R.drawable.gear2, 0);
        register("ispq-vc", "iSpQ VideoChat", R.drawable.gear2, 0);
        register("ishare", "iShare", R.drawable.gear2, 0);
        register("isticky", "iSticky", R.drawable.gear2, 0);
        register("istorm", "iStorm", R.drawable.gear2, 0);
        register("itis-device", "IT-IS International Ltd. Device", R.drawable.gear2, 0);
        register("itsrc", "iTunes Socket Remote Control", R.drawable.note, 0);
        register("ivef", "Inter VTS Exchange Format", R.drawable.gear2, 0);
        register("iwork", "iWork Server", R.drawable.gear2, 0);
        register("jcan", "Northrup Grumman/TASC/JCAN Protocol", R.drawable.gear2, 0);
        register("jeditx", "Jedit X", R.drawable.gear2, 0);
        register("jini", "Jini Service Discovery", R.drawable.gear2, 0);
        register("jtag", "Proprietary", R.drawable.gear2, 0);
        register("kerberos", "Kerberos", R.drawable.gear2, 0);
        register("kerberos-adm", "Kerberos Administration", R.drawable.gear2, 0);
        register("ktp", "Kabira Transaction Platform", R.drawable.gear2, 0);
        register("labyrinth", "Labyrinth local multiplayer protocol", R.drawable.gear2, 0);
        register("lan2p", "Lan2P Peer-to-Peer Network Protocol", R.drawable.network, 0);
        register("lapse", "Gawker", R.drawable.gear2, 0);
        register("lanrevagent", "LANrev Agent", R.drawable.gear2, 0);
        register("lanrevserver", "LANrev Server", R.drawable.gear2, 0);
        register("ldap", "Lightweight Directory Access Protocol", R.drawable.gear2, 0);
        register("leaf", "Lua Embedded Application Framework", R.drawable.gear2, 0);
        register("lexicon", "Lexicon Vocabulary Sharing", R.drawable.gear2, 0);
        register("liaison", "Liaison", R.drawable.gear2, 0);
        register("library", "Delicious Library 2 Collection Data Sharing Protocol", R.drawable.gear2, 0);
        register("llrp", "RFID reader Low Level Reader Protocol", R.drawable.gear2, 0);
        register("llrp-secure", "RFID reader Low Level Reader Protocol over SSL/TLS", R.drawable.gear2, 0);
        register("lobby", "Gobby", R.drawable.gear2, 0);
        register("logicnode", "Logic Pro Distributed Audio", R.drawable.note, 0);
        register("login", "Remote Login a la Telnet", R.drawable.gear2, 0);
        register("lonbridge", "Echelon LonBridge Server", R.drawable.gear2, 0);
        register("lontalk", "LonTalk over IP (ANSI 852)", R.drawable.gear2, 0);
        register("lonworks", "Echelon LNS Remote Client", R.drawable.gear2, 0);
        register("lsys-appserver", "Linksys One Application Server API", R.drawable.gear2, 0);
        register("lsys-camera", "Linksys One Camera API", R.drawable.gear2, 0);
        register("lsys-ezcfg", "LinkSys EZ Configuration", R.drawable.gear2, 0);
        register("lsys-oamp", "LinkSys Operations, Administration, Management, and Provisioning", R.drawable.gear2, 0);
        register("lux-dtp", "Lux Solis Data Transport Protocol", R.drawable.gear2, 0);
        register("lxi", "LXI", R.drawable.gear2, 0);
        register("lyrics", "iPod Lyrics Service", R.drawable.gear2, 0);
        register("macfoh", "MacFOH", R.drawable.gear2, 0);
        register("macfoh-admin", "MacFOH admin services", R.drawable.gear2, 0);
        register("macfoh-audio", "MacFOH audio stream", R.drawable.note, 0);
        register("macfoh-events", "MacFOH show control events", R.drawable.gear2, 0);
        register("macfoh-data", "MacFOH realtime data", R.drawable.gear2, 0);
        register("macfoh-db", "MacFOH database", R.drawable.gear2, 0);
        register("macfoh-remote", "MacFOH Remote", R.drawable.gear2, 0);
        register("macminder", "Mac Minder", R.drawable.gear2, 0);
        register("maestro", "Maestro Music Sharing Service", R.drawable.note, 0);
        register("magicdice", "Magic Dice Game Protocol", R.drawable.controller, 0);
        register("mandos", "Mandos Password Server", R.drawable.gear2, 0);
        register("matrix", "MATRIX Remote AV Switching", R.drawable.gear2, 0);
        register("mbconsumer", "MediaBroker++ Consumer", R.drawable.gear2, 0);
        register("mbproducer", "MediaBroker++ Producer", R.drawable.gear2, 0);
        register("mbserver", "MediaBroker++ Server", R.drawable.gear2, 0);
        register("mconnect", "ClairMail Connect", R.drawable.gear2, 0);
        register("mcrcp", "MediaCentral", R.drawable.gear2, 0);
        register("mediaboard1", "MediaBoardONE Asset and Information Manager data sharing and synchronization protocol", R.drawable.gear2, 0);
        register("mesamis", "Mes Amis", R.drawable.gear2, 0);
        register("mimer", "Mimer SQL Engine", R.drawable.gear2, 0);
        register("mi-raysat", "Mental Ray for Maya", R.drawable.gear2, 0);
        register("modolansrv", "modo LAN Services", R.drawable.gear2, 0);
        register("moneysync", "SplashMoney Synchronization Service", R.drawable.gear2, 0);
        register("moneyworks", "MoneyWorks Gold and MoneyWorks Datacentre network service", R.drawable.network, 0);
        register("moodring", "Bonjour Mood Ring tutorial program", R.drawable.gear2, 0);
        register("mother", "Mother script server protocol", R.drawable.gear2, 0);
        register("movieslate", "MovieSlate digital clapperboard", R.drawable.gear2, 0);
        register("mp3sushi", "MP3 Sushi", R.drawable.gear2, 0);
        register("mqtt", "IBM MQ Telemetry Transport Broker", R.drawable.gear2, 0);
        register("mslingshot", "Martian SlingShot", R.drawable.gear2, 0);
        register("mumble", "Mumble VoIP communication protocol", R.drawable.gear2, 0);
        register("musicmachine", "Protocol for a distributed music playing service", R.drawable.note, 0);
        register("mysync", "MySync Protocol", R.drawable.gear2, 0);
        register("mttp", "MenuTunes Sharing", R.drawable.gear2, 0);
        register("mxim-art2", "Maxim Integrated Products Automated Roadtest Mk II", R.drawable.gear2, 0);
        register("mxim-ice", "Maxim Integrated Products In-circuit Emulator", R.drawable.gear2, 0);
        register("mxs", "MatrixStore", R.drawable.gear2, 0);
        register("ncbroadcast", "Network Clipboard Broadcasts", R.drawable.gear2, 0);
        register("ncdirect", "Network Clipboard Direct Transfers", R.drawable.gear2, 0);
        register("ncsyncserver", "Network Clipboard Sync Server", R.drawable.gear2, 0);
        register("neoriders", "NeoRiders Client Discovery Protocol", R.drawable.gear2, 0);
        register("net-assistant", "Apple Remote Desktop", R.drawable.display, 0);
        register("net2display", "Vesa Net2Display", R.drawable.gear2, 0);
        register("netrestore", "NetRestore", R.drawable.gear2, 0);
        register("newton-dock", "Escale", R.drawable.gear2, 0);
        register("nfs", "Network File System - Sun Microsystems", R.drawable.cloud, 0);
        register("nssocketport", "DO over NSSocketPort", R.drawable.gear2, 0);
        register("ntlx-arch", "American Dynamics Intellex Archive Management Service", R.drawable.gear2, 0);
        register("ntlx-ent", "American Dynamics Intellex Enterprise Management Service", R.drawable.gear2, 0);
        register("ntlx-video", "American Dynamics Intellex Video Service", R.drawable.gear2, 0);
        register("ntp", "Network Time Protocol", R.drawable.network, 0);
        register("ntx", "Tenasys", R.drawable.gear2, 0);
        register("obf", "Observations Framework", R.drawable.gear2, 0);
        register("objective", "Means for clients to locate servers in an Objective (http://www.objective.com) instance.", R.drawable.gear2, 0);
        register("oce", "Oce Common Exchange Protocol", R.drawable.gear2, 0);
        register("od-master", "OpenDirectory Master", R.drawable.gear2, 0);
        register("odabsharing", "OD4Contact", R.drawable.gear2, 0);
        register("odisk", "Optical Disk Sharing", R.drawable.gear2, 0);
        register("officetime-sync", "OfficeTime Synchronization Protocol", R.drawable.gear2, 0);
        register("ofocus-conf", "OmniFocus setting configuration", R.drawable.gear2, 0);
        register("ofocus-sync", "OmniFocus document synchronization", R.drawable.notepad, 0);
        register("olpc-activity1", "One Laptop per Child activity", R.drawable.gear2, 0);
        register("oma-bcast-sg", "OMA BCAST Service Guide Discovery Service", R.drawable.gear2, 0);
        register("omni-bookmark", "OmniWeb", R.drawable.gear2, 0);
        register("omni-live", "Service for remote control of Omnisphere virtual instrument", R.drawable.gear2, 0);
        register("openbase", "OpenBase SQL", R.drawable.gear2, 0);
        register("opencu", "Conferencing Protocol", R.drawable.gear2, 0);
        register("oprofile", "oprofile server protocol", R.drawable.gear2, 0);
        register("oscit", "Open Sound Control Interface Transfer", R.drawable.gear2, 0);
        register("ovready", "ObjectVideo OV Ready Protocol", R.drawable.gear2, 0);
        register("owhttpd", "OWFS (1-wire file system) web server", R.drawable.spiderweb, 0);
        register("owserver", "OWFS (1-wire file system) server", R.drawable.gear2, 0);
        register("parentcontrol", "Remote Parental Controls", R.drawable.gear2, 0);
        register("passwordwallet", "PasswordWallet Data Synchronization Protocol", R.drawable.gear2, 0);
        register("pcast", "Mac OS X Podcast Producer Server", R.drawable.gear2, 0);
        register("p2pchat", "Peer-to-Peer Chat (Sample Java Bonjour application)", R.drawable.gear2, 0);
        register("panoply", "Panoply multimedia composite transfer protocol", R.drawable.gear2, 0);
        register("parabay-p2p", "Parabay P2P protocol", R.drawable.gear2, 0);
        register("parliant", "PhoneValet Anywhere", R.drawable.gear2, 0);
        register("pdl-datastream", "Printer Page Description Language Data Stream (vendor-specific)", R.drawable.printer, 2);
        register("pgpkey-hkp", "Horowitz Key Protocol (HKP)", R.drawable.gear2, 0);
        register("pgpkey-http", "PGP Keyserver using HTTP/1.1", R.drawable.spiderweb, 0);
        register("pgpkey-https", "PGP Keyserver using HTTPS", R.drawable.spiderweb, 0);
        register("pgpkey-ldap", "PGP Keyserver using LDAP", R.drawable.gear2, 0);
        register("pgpkey-mailto", "PGP Key submission using SMTP", R.drawable.envelope, 0);
        register("photoparata", "Photo Parata Event Photography Software", R.drawable.gear2, 0);
        register("pictua", "Pictua Intercommunication Protocol", R.drawable.gear2, 0);
        register("piesync", "pieSync Computer to Computer Synchronization", R.drawable.gear2, 0);
        register("piu", "Pedestal Interface Unit by RPM-PSI", R.drawable.gear2, 0);
        register("poch", "Parallel OperatiOn and Control Heuristic (Pooch)", R.drawable.gear2, 0);
        register("pokeeye", "Communication channel for \"Poke Eye\" Elgato EyeTV remote controller", R.drawable.gear2, 0);
        register("pop3", "Post Office Protocol - Version 3", R.drawable.envelope, 0);
        register("postgresql", "PostgreSQL Server", R.drawable.database, 0);
        register("powereasy-erp", "PowerEasy ERP", R.drawable.gear2, 0);
        register("powereasy-pos", "PowerEasy Point of Sale", R.drawable.gear2, 0);
        register("pplayer-ctrl", "Piano Player Remote Control", R.drawable.gear2, 0);
        register("presence", "Peer-to-peer messaging / Link-Local Messaging", R.drawable.chat, 0);
        register("print-caps", "Retrieve a description of a device's print capabilities", R.drawable.printer, 0);
        register("printer", "Spooler (more commonly known as \"LPR printing\" or \"LPD printing\")", R.drawable.printer, 2);
        register("profilemac", "Profile for Mac medical practice management software", R.drawable.gear2, 0);
        register("prolog", "Prolog", R.drawable.gear2, 0);
        register("protonet", "Protonet node and service discovery protocol", R.drawable.gear2, 0);
        register("psap", "Progal Service Advertising Protocol", R.drawable.gear2, 0);
        register("psia", "Physical Security Interoperability Alliance Protocol", R.drawable.gear2, 0);
        register("ptnetprosrv2", "PTNetPro Service", R.drawable.gear2, 0);
        register("ptp", "Picture Transfer Protocol", R.drawable.photos, 0);
        register("ptp-req", "PTP Initiation Request Protocol", R.drawable.photos, 0);
        register("puzzle", "Protocol used for puzzle games", R.drawable.controller, 0);
        register("qbox", "QBox Appliance Locator", R.drawable.gear2, 0);
        register("qttp", "QuickTime Transfer Protocol", R.drawable.gear2, 0);
        register("quinn", "Quinn Game Server", R.drawable.controller, 0);
        register("rakket", "Rakket Client Protocol", R.drawable.gear2, 0);
        register("radiotag", "RadioTAG: Event tagging for radio services", R.drawable.gear2, 0);
        register("radiovis", "RadioVIS: Visualisation for radio services", R.drawable.gear2, 0);
        register("radioepg", "RadioEPG: Electronic Programme Guide for radio services", R.drawable.gear2, 0);
        register("raop", "Remote Audio Output Protocol (AirTunes)", R.drawable.note, 0);
        register("rbr", "RBR Instrument Communication", R.drawable.gear2, 0);
        register("rce", "PowerCard", R.drawable.gear2, 0);
        register("rdp", "Windows Remote Desktop Protocol", R.drawable.display, 0);
        register("realplayfavs", "RealPlayer Shared Favorites", R.drawable.gear2, 0);
        register("recipe", "Recipe Sharing Protocol", R.drawable.gear2, 0);
        register("remote", "Remote Device Control Protocol", R.drawable.gear2, 0);
        register("remoteburn", "LaCie Remote Burn", R.drawable.gear2, 0);
        register("renderpipe", "ARTvps RenderDrive/PURE Renderer Protocol", R.drawable.gear2, 0);
        register("rendezvouspong", "RendezvousPong", R.drawable.gear2, 0);
        register("renkara-sync", "Renkara synchronization protocol", R.drawable.gear2, 0);
        register("resacommunity", "Community Service", R.drawable.gear2, 0);
        register("resol-vbus", "RESOL VBus", R.drawable.gear2, 0);
        register("retrospect", "Retrospect backup and restore service", R.drawable.gear2, 0);
        register("rfb", "Remote Frame Buffer (used by VNC)", R.drawable.display, 0);
        register("rfbc", "Remote Frame Buffer Client (Used by VNC viewers in listen-mode)", R.drawable.display, 0);
        register("rfid", "RFID Reader Mach1(tm) Protocol", R.drawable.gear2, 0);
        register("riousbprint", "Remote I/O USB Printer Protocol", R.drawable.printer, 0);
        register("roku-rcp", "Roku Control Protocol", R.drawable.gear2, 0);
        register("rql", "RemoteQuickLaunch", R.drawable.gear2, 0);
        register("rsmp-server", "Remote System Management Protocol (Server Instance)", R.drawable.gear2, 0);
        register("rsync", "Rsync", R.drawable.cloud, 0);
        register("rtsp", "Real Time Streaming Protocol", R.drawable.gear2, 0);
        register("rubygems", "RubyGems GemServer", R.drawable.gear2, 0);
        register("safarimenu", "Safari Menu", R.drawable.gear2, 0);
        register("sallingbridge", "Salling Clicker Sharing", R.drawable.gear2, 0);
        register("sallingclicker", "Salling Clicker Service", R.drawable.gear2, 0);
        register("salutafugijms", "Salutafugi Peer-To-Peer Java Message Service Implementation", R.drawable.gear2, 0);
        register("sandvox", "Sandvox", R.drawable.gear2, 0);
        register("sc-golf", "StrawberryCat Golf Protocol", R.drawable.gear2, 0);
        register("scanner", "Bonjour Scanning", R.drawable.gear2, 0);
        register("schick", "Schick", R.drawable.gear2, 0);
        register("scone", "Scone", R.drawable.gear2, 0);
        register("scpi-raw", "IEEE 488.2 (SCPI) Socket", R.drawable.gear2, 0);
        register("scpi-telnet", "IEEE 488.2 (SCPI) Telnet", R.drawable.gear2, 0);
        register("sdsharing", "Speed Download", R.drawable.gear2, 0);
        register("see", "SubEthaEdit 2", R.drawable.gear2, 0);
        register("seeCard", "seeCard", R.drawable.gear2, 0);
        register("senteo-http", "Senteo Assessment Software Protocol", R.drawable.spiderweb, 0);
        register("sentillion-vlc", "Sentillion Vault System", R.drawable.gear2, 0);
        register("sentillion-vlt", "Sentillion Vault Systems Cluster", R.drawable.gear2, 0);
        register("sepvsync", "SEPV Application Data Synchronization Protocol", R.drawable.gear2, 0);
        register("serendipd", "serendiPd Shared Patches for Pure Data", R.drawable.gear2, 0);
        register("servereye", "ServerEye AgentContainer Communication Protocol", R.drawable.gear2, 0);
        register("servermgr", "Mac OS X Server Admin", R.drawable.gear2, 0);
        register("services", "DNS Service Discovery", R.drawable.gear2, 0);
        register("sessionfs", "Session File Sharing", R.drawable.gear2, 0);
        register("sflow", "sFlow traffic monitoring", R.drawable.gear2, 0);
        register("sftp-ssh", "Secure File Transfer Protocol over SSH", R.drawable.cloud, 0);
        register("shell", "like exec, but automatic authentication is performed as for login server.", R.drawable.gear2, 0);
        register("shifter", "Window Shifter server protocol", R.drawable.gear2, 0);
        register("shipsgm", "Swift Office Ships", R.drawable.gear2, 0);
        register("shipsinvit", "Swift Office Ships", R.drawable.gear2, 0);
        register("shoppersync", "SplashShopper Synchronization Service", R.drawable.gear2, 0);
        register("shoutcast", "Nicecast", R.drawable.gear2, 0);
        register("simmon", "Medical simulation patient monitor syncronisation protocol", R.drawable.gear2, 0);
        register("simusoftpong", "simusoftpong iPhone game protocol", R.drawable.controller, 0);
        register("sip", "Session Initiation Protocol, signalling protocol for VoIP", R.drawable.phone, 0);
        register("sipuri", "Session Initiation Protocol Uniform Resource Identifier", R.drawable.gear2, 0);
        register("sironaxray", "Sirona Xray Protocol", R.drawable.gear2, 0);
        register("skype", "Skype", R.drawable.phone, 0);
        register("sleep-proxy", "Sleep Proxy Server", R.drawable.network, 0);
        register("slimcli", "SliMP3 Server Command-Line Interface", R.drawable.gear2, 0);
        register("slimhttp", "SliMP3 Server Web Interface", R.drawable.spiderweb, 0);
        register("smartenergy", "Smart Energy Profile", R.drawable.gear2, 0);
        register("smb", "Server Message Block over TCP/IP", R.drawable.gear2, 0);
        register("sms", "Short Text Message Sending and Delivery Status Service", R.drawable.chat, 0);
        register("soap", "Simple Object Access Protocol", R.drawable.gear2, 0);
        register("socketcloud", "Socketcloud distributed application framework", R.drawable.gear2, 0);
        register("sox", "Simple Object eXchange", R.drawable.gear2, 0);
        register("sparechange", "SpareChange data sharing protocol", R.drawable.gear2, 0);
        register("spearcat", "sPearCat Host Discovery", R.drawable.gear2, 0);
        register("spike", "Shared Clipboard Protocol", R.drawable.gear2, 0);
        register("spincrisis", "Spin Crisis", R.drawable.gear2, 0);
        register("spl-itunes", "launchTunes", R.drawable.gear2, 0);
        register("spr-itunes", "netTunes", R.drawable.gear2, 0);
        register("splashsync", "SplashData Synchronization Service", R.drawable.gear2, 0);
        register("ssh", "SSH Remote Login Protocol", R.drawable.network, 0);
        register("ssscreenshare", "Screen Sharing", R.drawable.display, 0);
        register("strateges", "Strateges", R.drawable.gear2, 0);
        register("sge-exec", "Sun Grid Engine (Execution Host)", R.drawable.gear2, 0);
        register("sge-qmaster", "Sun Grid Engine (Master)", R.drawable.gear2, 0);
        register("souschef", "SousChef Recipe Sharing Protocol", R.drawable.gear2, 0);
        register("sparql", "SPARQL Protocol and RDF Query Language", R.drawable.gear2, 0);
        register("stanza", "Lexcycle Stanza service for discovering shared books", R.drawable.gear2, 0);
        register("stickynotes", "Sticky Notes", R.drawable.notepad, 0);
        register("submission", "Message Submission", R.drawable.gear2, 0);
        register("supple", "Supple Service protocol", R.drawable.gear2, 0);
        register("surveillus", "Surveillus Networks Discovery Protocol", R.drawable.gear2, 0);
        register("svn", "Subversion", R.drawable.gear2, 0);
        register("swcards", "Signwave Card Sharing Protocol", R.drawable.gear2, 0);
        register("switcher", "Wireless home control remote control protocol", R.drawable.gear2, 0);
        register("swordfish", "Swordfish Protocol for Input/Output", R.drawable.gear2, 0);
        register("sxqdea", "Synchronize! Pro X", R.drawable.gear2, 0);
        register("sybase-tds", "Sybase Server", R.drawable.gear2, 0);
        register("syncopation", "Syncopation Synchronization Protocol by Sonzea", R.drawable.gear2, 0);
        register("syncqdea", "Synchronize! X Plus 2.0", R.drawable.gear2, 0);
        register("synergy", "Synergy Peer Discovery", R.drawable.gear2, 0);
        register("synksharing", "SynkSharing synchronization protocol", R.drawable.gear2, 0);
        register("taccounting", "Data Transmission and Synchronization", R.drawable.gear2, 0);
        register("tango", "Tango Remote Control Protocol", R.drawable.gear2, 0);
        register("tapinoma-ecs", "Tapinoma Easycontact receiver", R.drawable.gear2, 0);
        register("taskcoachsync", "Task Coach Two-way Synchronization Protocol for iPhone", R.drawable.gear2, 0);
        register("tbricks", "tbricks internal protocol", R.drawable.gear2, 0);
        register("tcode", "Time Code", R.drawable.gear2, 0);
        register("tcu", "Tracking Control Unit by RPM-PSI", R.drawable.gear2, 0);
        register("te-faxserver", "TE-SYSTEMS GmbH Fax Server Daemon", R.drawable.gear2, 0);
        register("teamlist", "ARTIS Team Task", R.drawable.gear2, 0);
        register("teleport", "teleport", R.drawable.gear2, 0);
        register("telnet", "Telnet", R.drawable.gear2, 0);
        register("tera-fsmgr", "Terascala Filesystem Manager Protocol", R.drawable.gear2, 0);
        register("tera-mp", "Terascala Maintenance Protocol", R.drawable.gear2, 0);
        register("tf-redeye", "ThinkFlood RedEye IR bridge", R.drawable.gear2, 0);
        register("tftp", "Trivial File Transfer", R.drawable.cloud, 0);
        register("thumbwrestling", "tinkerbuilt Thumb Wrestling game", R.drawable.controller, 0);
        register("ticonnectmgr", "TI Connect Manager Discovery Service", R.drawable.gear2, 0);
        register("timbuktu", "Timbuktu", R.drawable.gear2, 0);
        register("tinavigator", "TI Navigator Hub 1.0 Discovery Service", R.drawable.gear2, 0);
        register("tivo-hme", "TiVo Home Media Engine Protocol", R.drawable.tv, 0);
        register("tivo-music", "TiVo Music Protocol", R.drawable.tv, 0);
        register("tivo-photos", "TiVo Photos Protocol", R.drawable.tv, 0);
        register("tivo-remote", "TiVo Remote Protocol", R.drawable.tv, 0);
        register("tivo-videos", "TiVo Videos Protocol", R.drawable.tv, 0);
        register("todogwa", "2Do Sync Helper Tool for Mac OS X and PCs", R.drawable.gear2, 0);
        register("tomboy", "Tomboy", R.drawable.gear2, 0);
        register("toothpicserver", "ToothPics Dental Office Support Server", R.drawable.gear2, 0);
        register("touch-able", "iPhone and iPod touch Remote Controllable", R.drawable.iphone, 0);
        register("touch-remote", "iPhone and iPod touch Remote Pairing", R.drawable.iphone, 0);
        register("tri-vis-client", "triCerat Simplify Visibility Client", R.drawable.gear2, 0);
        register("tri-vis-server", "triCerat Simplify Visibility Server", R.drawable.gear2, 0);
        register("tryst", "Tryst", R.drawable.gear2, 0);
        register("tt4inarow", "Trivial Technology's 4 in a Row", R.drawable.gear2, 0);
        register("ttcheckers", "Trivial Technology's Checkers", R.drawable.gear2, 0);
        register("ttp4daemon", "TechTool Pro 4 Anti-Piracy Service", R.drawable.gear2, 0);
        register("tunage", "Tunage Media Control Service", R.drawable.gear2, 0);
        register("tuneranger", "TuneRanger", R.drawable.gear2, 0);
        register("ubertragen", "Ubertragen", R.drawable.gear2, 0);
        register("uddi", "Universal Description, Discovery and Integration", R.drawable.gear2, 0);
        register("uddi-inq", "Universal Description, Discovery and Integration Inquiry", R.drawable.gear2, 0);
        register("uddi-pub", "Universal Description, Discovery and Integration Publishing", R.drawable.gear2, 0);
        register("uddi-sub", "Universal Description, Discovery and Integration Subscription", R.drawable.gear2, 0);
        register("uddi-sec", "Universal Description, Discovery and Integration Security", R.drawable.gear2, 0);
        register("upnp", "Universal Plug and Play", R.drawable.gear2, 0);
        register("urlbookmark", "URL Advertising", R.drawable.gear2, 0);
        register("uswi", "Universal Switching Corporation products", R.drawable.gear2, 0);
        register("utest", "uTest", R.drawable.gear2, 0);
        register("uwsgi", "Unbit Web Server Gateway Interface", R.drawable.spiderweb, 0);
        register("ve-decoder", "American Dynamics VideoEdge Decoder Control Service", R.drawable.gear2, 0);
        register("ve-encoder", "American Dynamics VideoEdge Encoder Control Service", R.drawable.gear2, 0);
        register("ve-recorder", "American Dynamics VideoEdge Recorder Control Service", R.drawable.gear2, 0);
        register("visel", "visel Q-System services", R.drawable.gear2, 0);
        register("volley", "Volley", R.drawable.gear2, 0);
        register("vos", "Virtual Object System (using VOP/TCP)", R.drawable.gear2, 0);
        register("vue4rendercow", "VueProRenderCow", R.drawable.gear2, 0);
        register("vxi-11", "VXI-11 TCP/IP Instrument Protocol", R.drawable.gear2, 0);
        register("walkietalkie", "Walkie Talkie", R.drawable.gear2, 0);
        register("we-jell", "Proprietary collaborative messaging protocol", R.drawable.gear2, 0);
        register("webdav", "World Wide Web Distributed Authoring and Versioning (WebDAV)", R.drawable.cloud, 0);
        register("webdavs", "WebDAV over SSL/TLS", R.drawable.cloud, 0);
        register("webissync", "WebIS Sync Protocol", R.drawable.gear2, 0);
        register("wedraw", "weDraw document sharing protocol", R.drawable.notepad, 0);
        register("whamb", "Whamb", R.drawable.gear2, 0);
        register("whistler", "Honeywell Video Systems", R.drawable.tv, 0);
        register("wired", "Wired Server", R.drawable.gear2, 0);
        register("witap", "WiTap Sample Game Protocol", R.drawable.controller, 0);
        register("witapvoice", "witapvoice", R.drawable.gear2, 0);
        register("wkgrpsvr", "Workgroup Server Discovery", R.drawable.gear2, 0);
        register("workstation", "Workgroup Manager", R.drawable.network, 0);
        register("wormhole", "Roku Cascade Wormhole Protocol", R.drawable.gear2, 0);
        register("workgroup", "Novell collaboration workgroup", R.drawable.gear2, 0);
        register("writietalkie", "Writie Talkie Data Sharing", R.drawable.gear2, 0);
        register("ws", "Web Services", R.drawable.gear2, 0);
        register("wtc-heleos", "Wyatt Technology Corporation HELEOS", R.drawable.gear2, 0);
        register("wtc-qels", "Wyatt Technology Corporation QELS", R.drawable.gear2, 0);
        register("wtc-rex", "Wyatt Technology Corporation Optilab rEX", R.drawable.gear2, 0);
        register("wtc-viscostar", "Wyatt Technology Corporation ViscoStar", R.drawable.gear2, 0);
        register("wtc-wpr", "Wyatt Technology Corporation DynaPro Plate Reader", R.drawable.gear2, 0);
        register("wwdcpic", "PictureSharing sample code", R.drawable.gear2, 0);
        register("x-on", "x-on services synchronisation protocol", R.drawable.gear2, 0);
        register("x-plane9", "x-plane9", R.drawable.gear2, 0);
        register("xcodedistcc", "Xcode Distributed Compiler", R.drawable.network, 0);
        register("xgate-rmi", "xGate Remote Management Interface", R.drawable.gear2, 0);
        register("xgrid", "Xgrid", R.drawable.gear2, 0);
        register("xmms2", "XMMS2 IPC Protocol", R.drawable.gear2, 0);
        register("xmp", "Xperientia Mobile Protocol", R.drawable.gear2, 0);
        register("xmpp-client", "XMPP Client Connection", R.drawable.chat, 0);
        register("xmpp-server", "XMPP Server Connection", R.drawable.chat, 0);
        register("xsanclient", "Xsan Client", R.drawable.gear2, 0);
        register("xsanserver", "Xsan Server", R.drawable.gear2, 0);
        register("xsansystem", "Xsan System", R.drawable.gear2, 0);
        register("xserveraid", "XServe Raid", R.drawable.cloud, 0);
        register("xsync", "Xserve RAID Synchronization", R.drawable.gear2, 0);
        register("xtimelicence", "xTime License", R.drawable.gear2, 0);
        register("xtshapro", "xTime Project", R.drawable.gear2, 0);
        register("xul-http", "XUL (XML User Interface Language) transported over HTTP", R.drawable.spiderweb, 0);
        register("yakumo", "Yakumo iPhone OS Device Control Protocol", R.drawable.iphone, 0);
    }

    @Override
    public int compareTo(Object o) {
        if (o instanceof ServiceLookup) {
            return new Integer(priority).compareTo(new Integer(((ServiceLookup) o).priority));
        }
        return 0;
    }
}
