package org.movieos.flame;

import java.util.HashMap;

public class ServiceLookup implements Comparable {
    private static final String TAG = "SericeLookup";

    static HashMap<String, ServiceLookup> lookup = new HashMap<>();

    public static void register(String name, String description, int drawable, int priority) {
        ServiceLookup s = new ServiceLookup(name, description, drawable, priority);
        lookup.put(s.name, s);
    }

    public static ServiceLookup get(String name) {
        if (lookup.isEmpty()) firstRun();
        String key = name.split("\\.")[0].replace("_", "");
        return lookup.get(key);
    }

    String name;
    String description;
    int drawable;
    int priority;

    public ServiceLookup(String name, String description, int drawable, int priority) {
        super();
        this.name = name;
        this.description = description;
        this.drawable = drawable;
        this.priority = priority;
    }

    static void firstRun() {
        // custom things not in master list
        register("acp-sync", "Internet gateway device configuration protocol", 0, 0);
        register("appletv-v2", "Apple TV", 0, 5);
        register("airplay", "Airplay", 0, 4);
        register("slipstreamrem", "Slipstream / Spotify?", 0, 0); // TODO spotify only?
        register("hudson", "Hudson build server console", 0, 0);
        register("apple-mobdev", "iOS remote development / sync", 0, 0); // TODO not sure about this one

        // atc
        // 16122

        // this list built with the service_list_builder script, though I've added my own custom icons, which
        // is a pain
        register("1password", "1Password Password Manager data sharing and synchronization protocol", 0, 0);
        register("a-d-sync", "Altos Design Synchronization protocol", 0, 0);
        register("abi-instrument", "Applied Biosystems Universal Instrument Framework", 0, 0);
        register("accessdata-f2d", "FTK2 Database Discovery Service", 0, 0);
        register("accessdata-f2w", "FTK2 Backend Processing Agent Service", 0, 0);
        register("accessone", "Strix Systems 5S/AccessOne protocol", 0, 0);
        register("accountedge", "MYOB AccountEdge", 0, 0);
        register("acrobatsrv", "Adobe Acrobat", 0, 0);
        register("actionitems", "ActionItems", 0, 0);
        register("activeraid", "Active Storage Proprietary Device Management Protocol", 0, 0);
        register("activeraid-ssl", "Encrypted transport of Active Storage Proprietary Device Management Protocol", 0, 0);
        register("addressbook", "Address-O-Matic", 0, 0);
        register("adobe-vc", "Adobe Version Cue", 0, 0);
        register("adisk", "Automatic Disk Discovery", 0, 0);
        register("adpro-setup", "ADPRO Security Device Setup", 0, 0);
        register("aecoretech", "Apple Application Engineering Services", 0, 0);
        register("aeroflex", "Aeroflex instrumentation and software", 0, 0);
        register("afpovertcp", "Apple File Sharing", 0, 0);
        register("airport", "AirPort Base Station", 0, 3);
        register("airprojector", "AirProjector", 0, 0);
        register("airsharing", "Air Sharing", 0, 0);
        register("airsharingpro", "Air Sharing Pro", 0, 0);
        register("amba-cam", "Ambarella Cameras", 0, 0);
        register("amiphd-p2p", "P2PTapWar Sample Application from \"iPhone SDK Development\" Book", 0, 0);
        register("animolmd", "Animo License Manager", 0, 0);
        register("animobserver", "Animo Batch Server", 0, 0);
        register("anquetsync", "Anquet map synchronization between desktop and handheld devices", 0, 0);
        register("appelezvous", "Appelezvous", 0, 0);
        register("apple-ausend", "Apple Audio Units", 0, 0);
        register("apple-midi", "Apple MIDI", 0, 0);
        register("apple-sasl", "Apple Password Server", 0, 0);
        register("applerdbg", "Apple Remote Debug Services (OpenGL Profiler)", 0, 0);
        register("appletv", "Apple TV", 0, 4);
        register("appletv-itunes", "Apple TV discovery of iTunes", 0, 0);
        register("appletv-pair", "Apple TV Pairing", 0, 0);
        register("aquamon", "AquaMon", 0, 0);
        register("asr", "Apple Software Restore", 0, 0);
        register("astnotify", "Asterisk Caller-ID Notification Service", 0, 0);
        register("astralite", "Astralite", 0, 0);
        register("async", "address-o-sync", 0, 0);
        register("atlassianapp", "Atlassian Application (JIRA, Confluence, Fisheye, Crucible, Crowd, Bamboo) discovery service", 0, 0);
        register("av", "Allen Vanguard Hardware Service", 0, 0);
        register("axis-video", "Axis Video Cameras", 0, 0);
        register("auth", "Authentication Service", 0, 0);
        register("b3d-convince", "3M Unitek Digital Orthodontic System", 0, 0);
        register("babyphone", "BabyPhone", 0, 0);
        register("bdsk", "BibDesk Sharing", 0, 0);
        register("beacon", "Beacon Remote Service", 0, 0);
        register("beamer", "Beamer Data Sharing Protocol", 0, 0);
        register("beatpack", "BeatPack Synchronization Server for BeatMaker", 0, 0);
        register("beep", "Xgrid Technology Preview", 0, 0);
        register("bfagent", "BuildForge Agent", 0, 0);
        register("bigbangchess", "Big Bang Chess", 0, 0);
        register("bigbangmancala", "Big Bang Mancala", 0, 0);
        register("bittorrent", "BitTorrent Zeroconf Peer Discovery Protocol", 0, 0);
        register("blackbook", "Little Black Book Information Exchange Protocol", 0, 0);
        register("bluevertise", "BlueVertise Network Protocol (BNP)", 0, 0);
        register("bookworm", "Bookworm Client Discovery", 0, 0);
        register("bootps", "Bootstrap Protocol Server", 0, 0);
        register("boundaryscan", "Proprietary", 0, 0);
        register("bousg", "Bag Of Unusual Strategy Games", 0, 0);
        register("bri", "RFID Reader Basic Reader Interface", 0, 0);
        register("bsqdea", "Backup Simplicity", 0, 0);
        register("busycal", "BusySync Calendar Synchronization Protocol", 0, 0);
        register("caltalk", "CalTalk", 0, 0);
        register("cardsend", "Card Send Protocol", 0, 0);
        register("cctv", "IP and Closed-Circuit Television for Securitiy applications", 0, 0);
        register("cheat", "The Cheat", 0, 0);
        register("chess", "Project Gridlock", 0, 0);
        register("chfts", "Fluid Theme Server", 0, 0);
        register("chili", "The CHILI Radiology System", 0, 0);
        register("cip4discovery", "Discovery of JDF (CIP4 Job Definition Format) enabled devices", 0, 0);
        register("clipboard", "Clipboard Sharing", 0, 0);
        register("clique", "Clique Link-Local Multicast Chat Room", 0, 0);
        register("clscts", "Oracle CLS Cluster Topology Service", 0, 0);
        register("collection", "Published Collection Object", 0, 0);
        register("com-ocs-es-mcc", "ElectraStar media centre control protocol", 0, 0);
        register("contactserver", "Now Contact", 0, 0);
        register("corroboree", "Corroboree Server", 0, 0);
        register("cpnotebook2", "NoteBook 2", 0, 0);
        register("cvspserver", "CVS PServer", 0, 0);
        register("cw-codetap", "CodeWarrior HTI Xscale PowerTAP", 0, 0);
        register("cw-dpitap", "CodeWarrior HTI DPI PowerTAP", 0, 0);
        register("cw-oncetap", "CodeWarrior HTI OnCE PowerTAP", 0, 0);
        register("cw-powertap", "CodeWarrior HTI COP PowerTAP", 0, 0);
        register("cytv", "CyTV", 0, 0);
        register("daap", "Digital Audio Access Protocol (iTunes)", 0, 0);
        register("dacp", "Digital Audio Control Protocol (iTunes)", 0, 0);
        register("dancepartner", "Dance partner application for iPhone", 0, 0);
        register("dataturbine", "Open Source DataTurbine Streaming Data Middleware", 0, 0);
        register("device-info", "Device Info", 0, 0);
        register("difi", "EyeHome", 0, 0);
        register("disconnect", "DisConnect Peer to Peer Game Protocol", 0, 0);
        register("dist-opencl", "Distributed OpenCL discovery protocol", 0, 0);
        register("distcc", "Distributed Compiler", 0, 0);
        register("ditrios", "Ditrios SOA Framework Protocol", 0, 0);
        register("divelogsync", "Dive Log Data Sharing and Synchronization Protocol", 0, 0);
        register("dltimesync", "Local Area Dynamic Time Synchronisation Protocol", 0, 0);
        register("dns-llq", "DNS Long-Lived Queries", 0, 0);
        register("dns-sd", "DNS Service Discovery", 0, 0);
        register("dns-update", "DNS Dynamic Update Service", 0, 0);
        register("domain", "Domain Name Server", 0, 0);
        register("dop", "Roar (Death of Productivity)", 0, 0);
        register("dossier", "Vortimac Dossier Protocol", 0, 0);
        register("dpap", "Digital Photo Access Protocol (iPhoto)", 0, 0);
        register("dropcopy", "DropCopy", 0, 0);
        register("dsl-sync", "Data Synchronization Protocol for Discovery Software products", 0, 0);
        register("dtrmtdesktop", "Desktop Transporter Remote Desktop Protocol", 0, 0);
        register("dvbservdsc", "DVB Service Discovery", 0, 0);
        register("dxtgsync", "Documents To Go Desktop Sync Protocol", 0, 0);
        register("ea-dttx-poker", "Protocol for EA Downtown Texas Hold 'em", 0, 0);
        register("earphoria", "Earphoria", 0, 0);
        register("eb-amuzi", "Amuzi peer-to-peer session synchronization protocol", 0, 0);
        register("ebms", "ebXML Messaging", 0, 0);
        register("ecms", "Northrup Grumman/Mission Systems/ESL Data Flow Protocol", 0, 0);
        register("ebreg", "ebXML Registry", 0, 0);
        register("ecbyesfsgksc", "Net Monitor Anti-Piracy Service", 0, 0);
        register("edcp", "LaCie Ethernet Disk Configuration Protocol", 0, 0);
        register("egistix", "Egistix Auto-Discovery", 0, 0);
        register("eheap", "Interactive Room Software Infrastructure (Event Sharing)", 0, 0);
        register("embrace", "DataEnvoy", 0, 0);
        register("ep", "Endpoint Protocol (EP) for use in Home Automation systems", 0, 0);
        register("eppc", "Remote AppleEvents", 0, 0);
        register("erp-scale", "Pocket Programs ERP-Scale Server Discovery protocol", 0, 0);
        register("esp", "Extensis Server Protocol", 0, 0);
        register("eucalyptus", "Eucalyptus Discovery", 0, 0);
        register("eventserver", "Now Up-to-Date", 0, 0);
        register("evs-notif", "EVS Notification Center Protocol", 0, 0);
        register("ewalletsync", "Synchronization Protocol for Ilium Software's eWallet", 0, 0);
        register("example", "Example Service Type", 0, 0);
        register("exb", "Exbiblio Cascading Service Protocol", 0, 0);
        register("exec", "Remote Process Execution", 0, 0);
        register("extensissn", "Extensis Serial Number", 0, 0);
        register("eyetvsn", "EyeTV Sharing", 0, 0);
        register("facespan", "FaceSpan", 0, 0);
        register("fairview", "Fairview Device Identification", 0, 0);
        register("faxstfx", "FAXstf", 0, 0);
        register("feed-sharing", "NetNewsWire 2.0", 0, 0);
        register("firetask", "Firetask task sharing and synchronization protocol", 0, 0);
        register("fish", "Fish", 0, 0);
        register("fix", "Financial Information Exchange (FIX) Protocol", 0, 0);
        register("fjork", "Fjork", 0, 0);
        register("fl-purr", "FilmLight Cluster Power Control Service", 0, 0);
        register("fmpro-internal", "FileMaker Pro", 0, 0);
        register("fmserver-admin", "FileMaker Server Administration Communication Service", 0, 0);
        register("fontagentnode", "FontAgent Pro", 0, 0);
        register("foxtrot-serv", "FoxTrot Search Server Discovery Service", 0, 0);
        register("foxtrot-start", "FoxTrot Professional Search Discovery Service", 0, 0);
        register("frameforge-lic", "FrameForge License", 0, 0);
        register("freehand", "FreeHand MusicPad Pro Interface Protocol", 0, 0);
        register("frog", "Frog Navigation Systems", 0, 0);
        register("ftp", "File Transfer", 0, 0);
        register("ftpcroco", "Crocodile FTP Server", 0, 0);
        register("fv-cert", "Fairview Certificate", 0, 0);
        register("fv-key", "Fairview Key", 0, 0);
        register("fv-time", "Fairview Time/Date", 0, 0);
        register("garagepad", "Entrackment Client Service", 0, 0);
        register("gbs-smp", "SnapMail", 0, 0);
        register("gbs-stp", "SnapTalk", 0, 0);
        register("gforce-ssmp", "G-Force Control via SoundSpectrum's SSMP TCP Protocol", 0, 0);
        register("glasspad", "GlassPad Data Exchange Protocol", 0, 0);
        register("glasspadserver", "GlassPadServer Data Exchange Protocol", 0, 0);
        register("glrdrvmon", "OpenGL Driver Monitor", 0, 0);
        register("gpnp", "Grid Plug and Play", 0, 0);
        register("grillezvous", "Roxio ToastAnywhere(tm) Recorder Sharing", 0, 0);
        register("growl", "Growl", 0, 0);
        register("guid", "Special service type for resolving by GUID (Globally Unique Identifier)", 0, 0);
        register("h323", "H.323 Real-time audio, video and data communication call setup protocol", 0, 0);
        register("helix", "MultiUser Helix Server", 0, 0);
        register("help", "HELP command", 0, 0);
        register("hg", "Mercurial web-based repository access", 0, 0);
        register("hinz", "HINZMobil Synchronization protocol", 0, 0);
        register("hmcp", "Home Media Control Protocol", 0, 0);
        register("home-sharing", "iTunes Home Sharing", 0, 0);
        register("homeauto", "iDo Technology Home Automation Protocol", 0, 0);
        register("honeywell-vid", "Honeywell Video Systems", 0, 0);
        register("hotwayd", "Hotwayd", 0, 0);
        register("howdy", "Howdy messaging and notification protocol", 0, 0);
        register("hpr-bldlnx", "HP Remote Build System for Linux-based Systems", 0, 0);
        register("hpr-bldwin", "HP Remote Build System for Microsoft Windows Systems", 0, 0);
        register("hpr-db", "Identifies systems that house databases for the Remote Build System and Remote Test System", 0, 0);
        register("hpr-rep", "HP Remote Repository for Build and Test Results", 0, 0);
        register("hpr-toollnx", "HP Remote System that houses compilers and tools for Linux-based Systems", 0, 0);
        register("hpr-toolwin", "HP Remote System that houses compilers and tools for Microsoft Windows Systems", 0, 0);
        register("hpr-tstlnx", "HP Remote Test System for Linux-based Systems", 0, 0);
        register("hpr-tstwin", "HP Remote Test System for Microsoft Windows Systems", 0, 0);
        register("hs-off", "Hobbyist Software Off Discovery", 0, 0);
        register("htsp", "Home Tv Streaming Protocol", 0, 0);
        register("http", "World Wide Web HTML-over-HTTP", 0, 0);
        register("https", "HTTP over SSL/TLS", 0, 0);
        register("hydra", "SubEthaEdit", 0, 0);
        register("hyperstream", "Atempo HyperStream deduplication server", 0, 0);
        register("iax", "Inter Asterisk eXchange, ease-of-use NAT friendly open VoIP protocol", 0, 0);
        register("ibiz", "iBiz Server", 0, 0);
        register("ica-networking", "Image Capture Networking", 0, 0);
        register("ican", "Northrup Grumman/TASC/ICAN Protocol", 0, 0);
        register("ichalkboard", "iChalk", 0, 0);
        register("ichat", "iChat 1.0", 0, 0);
        register("iconquer", "iConquer", 0, 0);
        register("idata", "Generic Data Acquisition and Control Protocol", 0, 0);
        register("idsync", "SplashID Synchronization Service", 0, 0);
        register("ifolder", "Published iFolder", 0, 0);
        register("ihouse", "Idle Hands iHouse Protocol", 0, 0);
        register("ii-drills", "Instant Interactive Drills", 0, 0);
        register("ii-konane", "Instant Interactive Konane", 0, 0);
        register("ilynx", "iLynX", 0, 0);
        register("imap", "Internet Message Access Protocol", 0, 0);
        register("imidi", "iMidi", 0, 0);
        register("indigo-dvr", "Indigo Security Digital Video Recorders", 0, 0);
        register("inova-ontrack", "Inova Solutions OnTrack Display Protocol", 0, 0);
        register("idcws", "Intermec Device Configuration Web Services", 0, 0);
        register("ipbroadcaster", "IP Broadcaster", 0, 0);
        register("ipp", "IPP (Internet Printing Protocol)", 0, 0);
        register("ipspeaker", "IP Speaker Control Protocol", 0, 0);
        register("irelay", "iRelay application discovery service", 0, 0);
        register("irmc", "Intego Remote Management Console", 0, 0);
        register("iscsi", "Internet Small Computer Systems Interface (iSCSI)", 0, 0);
        register("isparx", "iSparx", 0, 0);
        register("ispq-vc", "iSpQ VideoChat", 0, 0);
        register("ishare", "iShare", 0, 0);
        register("isticky", "iSticky", 0, 0);
        register("istorm", "iStorm", 0, 0);
        register("itis-device", "IT-IS International Ltd. Device", 0, 0);
        register("itsrc", "iTunes Socket Remote Control", 0, 0);
        register("ivef", "Inter VTS Exchange Format", 0, 0);
        register("iwork", "iWork Server", 0, 0);
        register("jcan", "Northrup Grumman/TASC/JCAN Protocol", 0, 0);
        register("jeditx", "Jedit X", 0, 0);
        register("jini", "Jini Service Discovery", 0, 0);
        register("jtag", "Proprietary", 0, 0);
        register("kerberos", "Kerberos", 0, 0);
        register("kerberos-adm", "Kerberos Administration", 0, 0);
        register("ktp", "Kabira Transaction Platform", 0, 0);
        register("labyrinth", "Labyrinth local multiplayer protocol", 0, 0);
        register("lan2p", "Lan2P Peer-to-Peer Network Protocol", 0, 0);
        register("lapse", "Gawker", 0, 0);
        register("lanrevagent", "LANrev Agent", 0, 0);
        register("lanrevserver", "LANrev Server", 0, 0);
        register("ldap", "Lightweight Directory Access Protocol", 0, 0);
        register("leaf", "Lua Embedded Application Framework", 0, 0);
        register("lexicon", "Lexicon Vocabulary Sharing", 0, 0);
        register("liaison", "Liaison", 0, 0);
        register("library", "Delicious Library 2 Collection Data Sharing Protocol", 0, 0);
        register("llrp", "RFID reader Low Level Reader Protocol", 0, 0);
        register("llrp-secure", "RFID reader Low Level Reader Protocol over SSL/TLS", 0, 0);
        register("lobby", "Gobby", 0, 0);
        register("logicnode", "Logic Pro Distributed Audio", 0, 0);
        register("login", "Remote Login a la Telnet", 0, 0);
        register("lonbridge", "Echelon LonBridge Server", 0, 0);
        register("lontalk", "LonTalk over IP (ANSI 852)", 0, 0);
        register("lonworks", "Echelon LNS Remote Client", 0, 0);
        register("lsys-appserver", "Linksys One Application Server API", 0, 0);
        register("lsys-camera", "Linksys One Camera API", 0, 0);
        register("lsys-ezcfg", "LinkSys EZ Configuration", 0, 0);
        register("lsys-oamp", "LinkSys Operations, Administration, Management, and Provisioning", 0, 0);
        register("lux-dtp", "Lux Solis Data Transport Protocol", 0, 0);
        register("lxi", "LXI", 0, 0);
        register("lyrics", "iPod Lyrics Service", 0, 0);
        register("macfoh", "MacFOH", 0, 0);
        register("macfoh-admin", "MacFOH admin services", 0, 0);
        register("macfoh-audio", "MacFOH audio stream", 0, 0);
        register("macfoh-events", "MacFOH show control events", 0, 0);
        register("macfoh-data", "MacFOH realtime data", 0, 0);
        register("macfoh-db", "MacFOH database", 0, 0);
        register("macfoh-remote", "MacFOH Remote", 0, 0);
        register("macminder", "Mac Minder", 0, 0);
        register("maestro", "Maestro Music Sharing Service", 0, 0);
        register("magicdice", "Magic Dice Game Protocol", 0, 0);
        register("mandos", "Mandos Password Server", 0, 0);
        register("matrix", "MATRIX Remote AV Switching", 0, 0);
        register("mbconsumer", "MediaBroker++ Consumer", 0, 0);
        register("mbproducer", "MediaBroker++ Producer", 0, 0);
        register("mbserver", "MediaBroker++ Server", 0, 0);
        register("mconnect", "ClairMail Connect", 0, 0);
        register("mcrcp", "MediaCentral", 0, 0);
        register("mediaboard1", "MediaBoardONE Asset and Information Manager data sharing and synchronization protocol", 0, 0);
        register("mesamis", "Mes Amis", 0, 0);
        register("mimer", "Mimer SQL Engine", 0, 0);
        register("mi-raysat", "Mental Ray for Maya", 0, 0);
        register("modolansrv", "modo LAN Services", 0, 0);
        register("moneysync", "SplashMoney Synchronization Service", 0, 0);
        register("moneyworks", "MoneyWorks Gold and MoneyWorks Datacentre network service", 0, 0);
        register("moodring", "Bonjour Mood Ring tutorial program", 0, 0);
        register("mother", "Mother script server protocol", 0, 0);
        register("movieslate", "MovieSlate digital clapperboard", 0, 0);
        register("mp3sushi", "MP3 Sushi", 0, 0);
        register("mqtt", "IBM MQ Telemetry Transport Broker", 0, 0);
        register("mslingshot", "Martian SlingShot", 0, 0);
        register("mumble", "Mumble VoIP communication protocol", 0, 0);
        register("musicmachine", "Protocol for a distributed music playing service", 0, 0);
        register("mysync", "MySync Protocol", 0, 0);
        register("mttp", "MenuTunes Sharing", 0, 0);
        register("mxim-art2", "Maxim Integrated Products Automated Roadtest Mk II", 0, 0);
        register("mxim-ice", "Maxim Integrated Products In-circuit Emulator", 0, 0);
        register("mxs", "MatrixStore", 0, 0);
        register("ncbroadcast", "Network Clipboard Broadcasts", 0, 0);
        register("ncdirect", "Network Clipboard Direct Transfers", 0, 0);
        register("ncsyncserver", "Network Clipboard Sync Server", 0, 0);
        register("neoriders", "NeoRiders Client Discovery Protocol", 0, 0);
        register("net-assistant", "Apple Remote Desktop", 0, 0);
        register("net2display", "Vesa Net2Display", 0, 0);
        register("netrestore", "NetRestore", 0, 0);
        register("newton-dock", "Escale", 0, 0);
        register("nfs", "Network File System - Sun Microsystems", 0, 0);
        register("nssocketport", "DO over NSSocketPort", 0, 0);
        register("ntlx-arch", "American Dynamics Intellex Archive Management Service", 0, 0);
        register("ntlx-ent", "American Dynamics Intellex Enterprise Management Service", 0, 0);
        register("ntlx-video", "American Dynamics Intellex Video Service", 0, 0);
        register("ntp", "Network Time Protocol", 0, 0);
        register("ntx", "Tenasys", 0, 0);
        register("obf", "Observations Framework", 0, 0);
        register("objective", "Means for clients to locate servers in an Objective (http://www.objective.com) instance.", 0, 0);
        register("oce", "Oce Common Exchange Protocol", 0, 0);
        register("od-master", "OpenDirectory Master", 0, 0);
        register("odabsharing", "OD4Contact", 0, 0);
        register("odisk", "Optical Disk Sharing", 0, 0);
        register("officetime-sync", "OfficeTime Synchronization Protocol", 0, 0);
        register("ofocus-conf", "OmniFocus setting configuration", 0, 0);
        register("ofocus-sync", "OmniFocus document synchronization", 0, 0);
        register("olpc-activity1", "One Laptop per Child activity", 0, 0);
        register("oma-bcast-sg", "OMA BCAST Service Guide Discovery Service", 0, 0);
        register("omni-bookmark", "OmniWeb", 0, 0);
        register("omni-live", "Service for remote control of Omnisphere virtual instrument", 0, 0);
        register("openbase", "OpenBase SQL", 0, 0);
        register("opencu", "Conferencing Protocol", 0, 0);
        register("oprofile", "oprofile server protocol", 0, 0);
        register("oscit", "Open Sound Control Interface Transfer", 0, 0);
        register("ovready", "ObjectVideo OV Ready Protocol", 0, 0);
        register("owhttpd", "OWFS (1-wire file system) web server", 0, 0);
        register("owserver", "OWFS (1-wire file system) server", 0, 0);
        register("parentcontrol", "Remote Parental Controls", 0, 0);
        register("passwordwallet", "PasswordWallet Data Synchronization Protocol", 0, 0);
        register("pcast", "Mac OS X Podcast Producer Server", 0, 0);
        register("p2pchat", "Peer-to-Peer Chat (Sample Java Bonjour application)", 0, 0);
        register("panoply", "Panoply multimedia composite transfer protocol", 0, 0);
        register("parabay-p2p", "Parabay P2P protocol", 0, 0);
        register("parliant", "PhoneValet Anywhere", 0, 0);
        register("pdl-datastream", "Printer Page Description Language Data Stream (vendor-specific)", 0, 2);
        register("pgpkey-hkp", "Horowitz Key Protocol (HKP)", 0, 0);
        register("pgpkey-http", "PGP Keyserver using HTTP/1.1", 0, 0);
        register("pgpkey-https", "PGP Keyserver using HTTPS", 0, 0);
        register("pgpkey-ldap", "PGP Keyserver using LDAP", 0, 0);
        register("pgpkey-mailto", "PGP Key submission using SMTP", 0, 0);
        register("photoparata", "Photo Parata Event Photography Software", 0, 0);
        register("pictua", "Pictua Intercommunication Protocol", 0, 0);
        register("piesync", "pieSync Computer to Computer Synchronization", 0, 0);
        register("piu", "Pedestal Interface Unit by RPM-PSI", 0, 0);
        register("poch", "Parallel OperatiOn and Control Heuristic (Pooch)", 0, 0);
        register("pokeeye", "Communication channel for \"Poke Eye\" Elgato EyeTV remote controller", 0, 0);
        register("pop3", "Post Office Protocol - Version 3", 0, 0);
        register("postgresql", "PostgreSQL Server", 0, 0);
        register("powereasy-erp", "PowerEasy ERP", 0, 0);
        register("powereasy-pos", "PowerEasy Point of Sale", 0, 0);
        register("pplayer-ctrl", "Piano Player Remote Control", 0, 0);
        register("presence", "Peer-to-peer messaging / Link-Local Messaging", 0, 0);
        register("print-caps", "Retrieve a description of a device's print capabilities", 0, 0);
        register("printer", "Spooler (more commonly known as \"LPR printing\" or \"LPD printing\")", 0, 2);
        register("profilemac", "Profile for Mac medical practice management software", 0, 0);
        register("prolog", "Prolog", 0, 0);
        register("protonet", "Protonet node and service discovery protocol", 0, 0);
        register("psap", "Progal Service Advertising Protocol", 0, 0);
        register("psia", "Physical Security Interoperability Alliance Protocol", 0, 0);
        register("ptnetprosrv2", "PTNetPro Service", 0, 0);
        register("ptp", "Picture Transfer Protocol", 0, 0);
        register("ptp-req", "PTP Initiation Request Protocol", 0, 0);
        register("puzzle", "Protocol used for puzzle games", 0, 0);
        register("qbox", "QBox Appliance Locator", 0, 0);
        register("qttp", "QuickTime Transfer Protocol", 0, 0);
        register("quinn", "Quinn Game Server", 0, 0);
        register("rakket", "Rakket Client Protocol", 0, 0);
        register("radiotag", "RadioTAG: Event tagging for radio services", 0, 0);
        register("radiovis", "RadioVIS: Visualisation for radio services", 0, 0);
        register("radioepg", "RadioEPG: Electronic Programme Guide for radio services", 0, 0);
        register("raop", "Remote Audio Output Protocol (AirTunes)", 0, 0);
        register("rbr", "RBR Instrument Communication", 0, 0);
        register("rce", "PowerCard", 0, 0);
        register("rdp", "Windows Remote Desktop Protocol", 0, 0);
        register("realplayfavs", "RealPlayer Shared Favorites", 0, 0);
        register("recipe", "Recipe Sharing Protocol", 0, 0);
        register("remote", "Remote Device Control Protocol", 0, 0);
        register("remoteburn", "LaCie Remote Burn", 0, 0);
        register("renderpipe", "ARTvps RenderDrive/PURE Renderer Protocol", 0, 0);
        register("rendezvouspong", "RendezvousPong", 0, 0);
        register("renkara-sync", "Renkara synchronization protocol", 0, 0);
        register("resacommunity", "Community Service", 0, 0);
        register("resol-vbus", "RESOL VBus", 0, 0);
        register("retrospect", "Retrospect backup and restore service", 0, 0);
        register("rfb", "Remote Frame Buffer (used by VNC)", 0, 0);
        register("rfbc", "Remote Frame Buffer Client (Used by VNC viewers in listen-mode)", 0, 0);
        register("rfid", "RFID Reader Mach1(tm) Protocol", 0, 0);
        register("riousbprint", "Remote I/O USB Printer Protocol", 0, 0);
        register("roku-rcp", "Roku Control Protocol", 0, 0);
        register("rql", "RemoteQuickLaunch", 0, 0);
        register("rsmp-server", "Remote System Management Protocol (Server Instance)", 0, 0);
        register("rsync", "Rsync", 0, 0);
        register("rtsp", "Real Time Streaming Protocol", 0, 0);
        register("rubygems", "RubyGems GemServer", 0, 0);
        register("safarimenu", "Safari Menu", 0, 0);
        register("sallingbridge", "Salling Clicker Sharing", 0, 0);
        register("sallingclicker", "Salling Clicker Service", 0, 0);
        register("salutafugijms", "Salutafugi Peer-To-Peer Java Message Service Implementation", 0, 0);
        register("sandvox", "Sandvox", 0, 0);
        register("sc-golf", "StrawberryCat Golf Protocol", 0, 0);
        register("scanner", "Bonjour Scanning", 0, 0);
        register("schick", "Schick", 0, 0);
        register("scone", "Scone", 0, 0);
        register("scpi-raw", "IEEE 488.2 (SCPI) Socket", 0, 0);
        register("scpi-telnet", "IEEE 488.2 (SCPI) Telnet", 0, 0);
        register("sdsharing", "Speed Download", 0, 0);
        register("see", "SubEthaEdit 2", 0, 0);
        register("seeCard", "seeCard", 0, 0);
        register("senteo-http", "Senteo Assessment Software Protocol", 0, 0);
        register("sentillion-vlc", "Sentillion Vault System", 0, 0);
        register("sentillion-vlt", "Sentillion Vault Systems Cluster", 0, 0);
        register("sepvsync", "SEPV Application Data Synchronization Protocol", 0, 0);
        register("serendipd", "serendiPd Shared Patches for Pure Data", 0, 0);
        register("servereye", "ServerEye AgentContainer Communication Protocol", 0, 0);
        register("servermgr", "Mac OS X Server Admin", 0, 0);
        register("services", "DNS Service Discovery", 0, 0);
        register("sessionfs", "Session File Sharing", 0, 0);
        register("sflow", "sFlow traffic monitoring", 0, 0);
        register("sftp-ssh", "Secure File Transfer Protocol over SSH", 0, 0);
        register("shell", "like exec, but automatic authentication is performed as for login server.", 0, 0);
        register("shifter", "Window Shifter server protocol", 0, 0);
        register("shipsgm", "Swift Office Ships", 0, 0);
        register("shipsinvit", "Swift Office Ships", 0, 0);
        register("shoppersync", "SplashShopper Synchronization Service", 0, 0);
        register("shoutcast", "Nicecast", 0, 0);
        register("simmon", "Medical simulation patient monitor syncronisation protocol", 0, 0);
        register("simusoftpong", "simusoftpong iPhone game protocol", 0, 0);
        register("sip", "Session Initiation Protocol, signalling protocol for VoIP", 0, 0);
        register("sipuri", "Session Initiation Protocol Uniform Resource Identifier", 0, 0);
        register("sironaxray", "Sirona Xray Protocol", 0, 0);
        register("skype", "Skype", 0, 0);
        register("sleep-proxy", "Sleep Proxy Server", 0, 0);
        register("slimcli", "SliMP3 Server Command-Line Interface", 0, 0);
        register("slimhttp", "SliMP3 Server Web Interface", 0, 0);
        register("smartenergy", "Smart Energy Profile", 0, 0);
        register("smb", "Server Message Block over TCP/IP", 0, 0);
        register("sms", "Short Text Message Sending and Delivery Status Service", 0, 0);
        register("soap", "Simple Object Access Protocol", 0, 0);
        register("socketcloud", "Socketcloud distributed application framework", 0, 0);
        register("sox", "Simple Object eXchange", 0, 0);
        register("sparechange", "SpareChange data sharing protocol", 0, 0);
        register("spearcat", "sPearCat Host Discovery", 0, 0);
        register("spike", "Shared Clipboard Protocol", 0, 0);
        register("spincrisis", "Spin Crisis", 0, 0);
        register("spl-itunes", "launchTunes", 0, 0);
        register("spr-itunes", "netTunes", 0, 0);
        register("splashsync", "SplashData Synchronization Service", 0, 0);
        register("ssh", "SSH Remote Login Protocol", 0, 0);
        register("ssscreenshare", "Screen Sharing", 0, 0);
        register("strateges", "Strateges", 0, 0);
        register("sge-exec", "Sun Grid Engine (Execution Host)", 0, 0);
        register("sge-qmaster", "Sun Grid Engine (Master)", 0, 0);
        register("souschef", "SousChef Recipe Sharing Protocol", 0, 0);
        register("sparql", "SPARQL Protocol and RDF Query Language", 0, 0);
        register("stanza", "Lexcycle Stanza service for discovering shared books", 0, 0);
        register("stickynotes", "Sticky Notes", 0, 0);
        register("submission", "Message Submission", 0, 0);
        register("supple", "Supple Service protocol", 0, 0);
        register("surveillus", "Surveillus Networks Discovery Protocol", 0, 0);
        register("svn", "Subversion", 0, 0);
        register("swcards", "Signwave Card Sharing Protocol", 0, 0);
        register("switcher", "Wireless home control remote control protocol", 0, 0);
        register("swordfish", "Swordfish Protocol for Input/Output", 0, 0);
        register("sxqdea", "Synchronize! Pro X", 0, 0);
        register("sybase-tds", "Sybase Server", 0, 0);
        register("syncopation", "Syncopation Synchronization Protocol by Sonzea", 0, 0);
        register("syncqdea", "Synchronize! X Plus 2.0", 0, 0);
        register("synergy", "Synergy Peer Discovery", 0, 0);
        register("synksharing", "SynkSharing synchronization protocol", 0, 0);
        register("taccounting", "Data Transmission and Synchronization", 0, 0);
        register("tango", "Tango Remote Control Protocol", 0, 0);
        register("tapinoma-ecs", "Tapinoma Easycontact receiver", 0, 0);
        register("taskcoachsync", "Task Coach Two-way Synchronization Protocol for iPhone", 0, 0);
        register("tbricks", "tbricks internal protocol", 0, 0);
        register("tcode", "Time Code", 0, 0);
        register("tcu", "Tracking Control Unit by RPM-PSI", 0, 0);
        register("te-faxserver", "TE-SYSTEMS GmbH Fax Server Daemon", 0, 0);
        register("teamlist", "ARTIS Team Task", 0, 0);
        register("teleport", "teleport", 0, 0);
        register("telnet", "Telnet", 0, 0);
        register("tera-fsmgr", "Terascala Filesystem Manager Protocol", 0, 0);
        register("tera-mp", "Terascala Maintenance Protocol", 0, 0);
        register("tf-redeye", "ThinkFlood RedEye IR bridge", 0, 0);
        register("tftp", "Trivial File Transfer", 0, 0);
        register("thumbwrestling", "tinkerbuilt Thumb Wrestling game", 0, 0);
        register("ticonnectmgr", "TI Connect Manager Discovery Service", 0, 0);
        register("timbuktu", "Timbuktu", 0, 0);
        register("tinavigator", "TI Navigator Hub 1.0 Discovery Service", 0, 0);
        register("tivo-hme", "TiVo Home Media Engine Protocol", 0, 0);
        register("tivo-music", "TiVo Music Protocol", 0, 0);
        register("tivo-photos", "TiVo Photos Protocol", 0, 0);
        register("tivo-remote", "TiVo Remote Protocol", 0, 0);
        register("tivo-videos", "TiVo Videos Protocol", 0, 0);
        register("todogwa", "2Do Sync Helper Tool for Mac OS X and PCs", 0, 0);
        register("tomboy", "Tomboy", 0, 0);
        register("toothpicserver", "ToothPics Dental Office Support Server", 0, 0);
        register("touch-able", "iPhone and iPod touch Remote Controllable", 0, 0);
        register("touch-remote", "iPhone and iPod touch Remote Pairing", 0, 0);
        register("tri-vis-client", "triCerat Simplify Visibility Client", 0, 0);
        register("tri-vis-server", "triCerat Simplify Visibility Server", 0, 0);
        register("tryst", "Tryst", 0, 0);
        register("tt4inarow", "Trivial Technology's 4 in a Row", 0, 0);
        register("ttcheckers", "Trivial Technology's Checkers", 0, 0);
        register("ttp4daemon", "TechTool Pro 4 Anti-Piracy Service", 0, 0);
        register("tunage", "Tunage Media Control Service", 0, 0);
        register("tuneranger", "TuneRanger", 0, 0);
        register("ubertragen", "Ubertragen", 0, 0);
        register("uddi", "Universal Description, Discovery and Integration", 0, 0);
        register("uddi-inq", "Universal Description, Discovery and Integration Inquiry", 0, 0);
        register("uddi-pub", "Universal Description, Discovery and Integration Publishing", 0, 0);
        register("uddi-sub", "Universal Description, Discovery and Integration Subscription", 0, 0);
        register("uddi-sec", "Universal Description, Discovery and Integration Security", 0, 0);
        register("upnp", "Universal Plug and Play", 0, 0);
        register("urlbookmark", "URL Advertising", 0, 0);
        register("uswi", "Universal Switching Corporation products", 0, 0);
        register("utest", "uTest", 0, 0);
        register("uwsgi", "Unbit Web Server Gateway Interface", 0, 0);
        register("ve-decoder", "American Dynamics VideoEdge Decoder Control Service", 0, 0);
        register("ve-encoder", "American Dynamics VideoEdge Encoder Control Service", 0, 0);
        register("ve-recorder", "American Dynamics VideoEdge Recorder Control Service", 0, 0);
        register("visel", "visel Q-System services", 0, 0);
        register("volley", "Volley", 0, 0);
        register("vos", "Virtual Object System (using VOP/TCP)", 0, 0);
        register("vue4rendercow", "VueProRenderCow", 0, 0);
        register("vxi-11", "VXI-11 TCP/IP Instrument Protocol", 0, 0);
        register("walkietalkie", "Walkie Talkie", 0, 0);
        register("we-jell", "Proprietary collaborative messaging protocol", 0, 0);
        register("webdav", "World Wide Web Distributed Authoring and Versioning (WebDAV)", 0, 0);
        register("webdavs", "WebDAV over SSL/TLS", 0, 0);
        register("webissync", "WebIS Sync Protocol", 0, 0);
        register("wedraw", "weDraw document sharing protocol", 0, 0);
        register("whamb", "Whamb", 0, 0);
        register("whistler", "Honeywell Video Systems", 0, 0);
        register("wired", "Wired Server", 0, 0);
        register("witap", "WiTap Sample Game Protocol", 0, 0);
        register("witapvoice", "witapvoice", 0, 0);
        register("wkgrpsvr", "Workgroup Server Discovery", 0, 0);
        register("workstation", "Workgroup Manager", 0, 0);
        register("wormhole", "Roku Cascade Wormhole Protocol", 0, 0);
        register("workgroup", "Novell collaboration workgroup", 0, 0);
        register("writietalkie", "Writie Talkie Data Sharing", 0, 0);
        register("ws", "Web Services", 0, 0);
        register("wtc-heleos", "Wyatt Technology Corporation HELEOS", 0, 0);
        register("wtc-qels", "Wyatt Technology Corporation QELS", 0, 0);
        register("wtc-rex", "Wyatt Technology Corporation Optilab rEX", 0, 0);
        register("wtc-viscostar", "Wyatt Technology Corporation ViscoStar", 0, 0);
        register("wtc-wpr", "Wyatt Technology Corporation DynaPro Plate Reader", 0, 0);
        register("wwdcpic", "PictureSharing sample code", 0, 0);
        register("x-on", "x-on services synchronisation protocol", 0, 0);
        register("x-plane9", "x-plane9", 0, 0);
        register("xcodedistcc", "Xcode Distributed Compiler", 0, 0);
        register("xgate-rmi", "xGate Remote Management Interface", 0, 0);
        register("xgrid", "Xgrid", 0, 0);
        register("xmms2", "XMMS2 IPC Protocol", 0, 0);
        register("xmp", "Xperientia Mobile Protocol", 0, 0);
        register("xmpp-client", "XMPP Client Connection", 0, 0);
        register("xmpp-server", "XMPP Server Connection", 0, 0);
        register("xsanclient", "Xsan Client", 0, 0);
        register("xsanserver", "Xsan Server", 0, 0);
        register("xsansystem", "Xsan System", 0, 0);
        register("xserveraid", "XServe Raid", 0, 0);
        register("xsync", "Xserve RAID Synchronization", 0, 0);
        register("xtimelicence", "xTime License", 0, 0);
        register("xtshapro", "xTime Project", 0, 0);
        register("xul-http", "XUL (XML User Interface Language) transported over HTTP", 0, 0);
        register("yakumo", "Yakumo iPhone OS Device Control Protocol", 0, 0);
    }

    @Override
    public int compareTo(Object o) {
        if (o instanceof ServiceLookup) {
            ServiceLookup s = (ServiceLookup) o;
            return Integer.valueOf(priority).compareTo(s.priority);
        }
        return 0;
    }


    public String getDescription() {
        return description;
    }

    public int getDrawable() {
        return drawable;
    }

    public int getPriority() {
        return priority;
    }
}


